droptablessp = "DROP TABLE SSP_DIM;"
droptablesdeal         = "DROP TABLE DEAL_DIM;"
droptablesadvertiser  = "DROP TABLE ADVERTISER_DIM;"
droptablescountry         = "DROP TABLE COUNTRY_DIM;"
droptablesagency          = "DROP TABLE AGENCY_DIM;"
droptablesproperty          = "DROP TABLE PROPERTY_DIM;"
droptablesmarketplace           = "DROP TABLE MARKETPLACE_DIM;"
droptablesdevicecategory          = "DROP TABLE DEVICE_CATEGORY_DIM;"
